name: Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install && npm run build
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: src # 如果你的打包文件夹名叫 build，请改为 build
          branch: gh-pages # 自动化程序会把编译好的代码放在这个分支
